language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv rehash
  - composer require satooshi/php-coveralls "^1" --no-update --dev
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v

cache:
  - vendor
